// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Comment     string
	Project     string
	Roles       string
	User        string
	UserRoles   string
	Userprofile string
}{
	Comment:     "comment",
	Project:     "project",
	Roles:       "roles",
	User:        "user",
	UserRoles:   "user_roles",
	Userprofile: "userprofile",
}
