// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Comments", testCommentsUpsert)

	t.Run("Projects", testProjectsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("UserRoles", testUserRolesUpsert)

	t.Run("Userprofiles", testUserprofilesUpsert)
}
