// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserprofiles(t *testing.T) {
	t.Parallel()

	query := Userprofiles()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserprofilesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserprofilesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Userprofiles().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserprofilesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserprofileSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserprofilesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserprofileExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Userprofile exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserprofileExists to return true, but got false.")
	}
}

func testUserprofilesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userprofileFound, err := FindUserprofile(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userprofileFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserprofilesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Userprofiles().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserprofilesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Userprofiles().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserprofilesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userprofileOne := &Userprofile{}
	userprofileTwo := &Userprofile{}
	if err = randomize.Struct(seed, userprofileOne, userprofileDBTypes, false, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}
	if err = randomize.Struct(seed, userprofileTwo, userprofileDBTypes, false, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userprofileOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userprofileTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Userprofiles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserprofilesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userprofileOne := &Userprofile{}
	userprofileTwo := &Userprofile{}
	if err = randomize.Struct(seed, userprofileOne, userprofileDBTypes, false, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}
	if err = randomize.Struct(seed, userprofileTwo, userprofileDBTypes, false, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userprofileOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userprofileTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userprofileBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Userprofile) error {
	*o = Userprofile{}
	return nil
}

func userprofileAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Userprofile) error {
	*o = Userprofile{}
	return nil
}

func userprofileAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Userprofile) error {
	*o = Userprofile{}
	return nil
}

func userprofileBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Userprofile) error {
	*o = Userprofile{}
	return nil
}

func userprofileAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Userprofile) error {
	*o = Userprofile{}
	return nil
}

func userprofileBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Userprofile) error {
	*o = Userprofile{}
	return nil
}

func userprofileAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Userprofile) error {
	*o = Userprofile{}
	return nil
}

func userprofileBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Userprofile) error {
	*o = Userprofile{}
	return nil
}

func userprofileAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Userprofile) error {
	*o = Userprofile{}
	return nil
}

func testUserprofilesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Userprofile{}
	o := &Userprofile{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userprofileDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Userprofile object: %s", err)
	}

	AddUserprofileHook(boil.BeforeInsertHook, userprofileBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userprofileBeforeInsertHooks = []UserprofileHook{}

	AddUserprofileHook(boil.AfterInsertHook, userprofileAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userprofileAfterInsertHooks = []UserprofileHook{}

	AddUserprofileHook(boil.AfterSelectHook, userprofileAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userprofileAfterSelectHooks = []UserprofileHook{}

	AddUserprofileHook(boil.BeforeUpdateHook, userprofileBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userprofileBeforeUpdateHooks = []UserprofileHook{}

	AddUserprofileHook(boil.AfterUpdateHook, userprofileAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userprofileAfterUpdateHooks = []UserprofileHook{}

	AddUserprofileHook(boil.BeforeDeleteHook, userprofileBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userprofileBeforeDeleteHooks = []UserprofileHook{}

	AddUserprofileHook(boil.AfterDeleteHook, userprofileAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userprofileAfterDeleteHooks = []UserprofileHook{}

	AddUserprofileHook(boil.BeforeUpsertHook, userprofileBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userprofileBeforeUpsertHooks = []UserprofileHook{}

	AddUserprofileHook(boil.AfterUpsertHook, userprofileAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userprofileAfterUpsertHooks = []UserprofileHook{}
}

func testUserprofilesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserprofilesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userprofileColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserprofileToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Userprofile
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userprofileDBTypes, false, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserprofileSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Userprofile)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserprofileToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Userprofile
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userprofileDBTypes, false, strmangle.SetComplement(userprofilePrimaryKeyColumns, userprofileColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Userprofiles[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testUserprofilesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserprofilesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserprofileSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserprofilesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Userprofiles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userprofileDBTypes = map[string]string{`ID`: `int`, `UserID`: `int`, `Email`: `varchar`, `Name`: `varchar`, `LastName`: `varchar`, `Photo`: `varchar`, `Adress`: `varchar`, `Phone`: `varchar`}
	_                  = bytes.MinRead
)

func testUserprofilesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userprofilePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userprofileAllColumns) == len(userprofilePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofilePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserprofilesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userprofileAllColumns) == len(userprofilePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Userprofile{}
	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userprofileDBTypes, true, userprofilePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userprofileAllColumns, userprofilePrimaryKeyColumns) {
		fields = userprofileAllColumns
	} else {
		fields = strmangle.SetComplement(
			userprofileAllColumns,
			userprofilePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserprofileSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserprofilesUpsert(t *testing.T) {
	t.Parallel()

	if len(userprofileAllColumns) == len(userprofilePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLUserprofileUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Userprofile{}
	if err = randomize.Struct(seed, &o, userprofileDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Userprofile: %s", err)
	}

	count, err := Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userprofileDBTypes, false, userprofilePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Userprofile struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Userprofile: %s", err)
	}

	count, err = Userprofiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
